[package]
name = "omavision"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "omavision"

[dependencies]
omavision-core = { path = "../core" }
anyhow.workspace = true
log.workspace = true
slint = "1.18"
clap = { version = "4", features = ["derive"] }
notify = "8"

[build-dependencies]
slint-build = "1.18"
